### ISSUE TITLE
Some more problems...

### ISSUE THREAD

**Issue by mengshanfeng** [AbductiveLearning/ABL-HED#2]
Hi, there:

I have successfully recurrented your code with the help of your README.md and the changes of the swipl initialising argument format. 

However, I have some other problems here:

1. How to accomplish a 'minus' version?

I have noticed that in the src/logic/prolog/BK.pl and learn_add.pl you define the Background Knowledge as
well as the 'addition rule'.

In the BK.pl, you define the 'Bir-wise operation':

%%%%%%%%%%%%%%%%%%%%%%
%% Bit-wise operation
%%%%%%%%%%%%%%%%%%%%%%
% Abductive calculation with given pseudo-labels, abduces pseudo-labels as well as operation rules
calc(Rules, Pseudo) :-
    calc([], Rules, Pseudo).
calc(Rules0, Rules1, Pseudo) :-
    parse_eq(Pseudo, eq(X,Y,Z)),
    bitwise_calc(Rules0, Rules1, X, Y, Z).

% Bit-wise calculation that handles carrying
bitwise_calc(Rules, Rules1, X, Y, Z) :-
    reverse(X, X1), reverse(Y, Y1), reverse(Z, Z1),
    bitwise_calc_r(Rules, Rules1, X1, Y1, Z1),
    maplist(digits, [X,Y,Z]).
bitwise_calc_r(Rs, Rs, [], Y, Y).
bitwise_calc_r(Rs, Rs, X, [], X).
bitwise_calc_r(Rules, Rules1, [D1 | X], [D2 | Y], [D3 | Z]) :-
    abduce_op_rule(my_op([D1],[D2],Sum), Rules, Rules2),
    ((Sum = [D3], Carry = []); (Sum = [C, D3], Carry = [C])),
    bitwise_calc_r(Rules2, Rules3, X, Carry, X_carried),
    bitwise_calc_r(Rules3, Rules1, X_carried, Y, Z).

I just change the folloeing 2 lines:

	bitwise_calc_r(Rs, Rs, [], Y, Y).
	bitwise_calc_r(Rs, Rs, X, [], X).

to 

	bitwise_calc_r(Rs, Rs, Y, Y, []).
	bitwise_calc_r(Rs, Rs, X, [], X).

to make the MINUS version of this equation as well as some other changes labeled with 'Some changes are made here.' in the 'BK_minus.pl' and no other changes are made.

However, it seemed that I failed.

I also note that in the readme, you says:
   The mapping from CNN to symbolic primitive symbols are learned, so it is fine
   if ABL learns `0+0=01` and `1+1=1`, it just swaps the semantics of `0` and `1`.

Can we add some more BK to avoid this? If possible, how?

2. How about altering the format of Equatios?

In your code, the Equation is like:

	X + Y = Z.

However, if I want to have another kind of format, for example:

	X = Y + Z.

What shoule I do? How about this:

	bitwise_calc_r(Rs, Rs, Y, Y, []).
	bitwise_calc_r(Rs, Rs, X, [], X).

Hopefully it works. Some other changes labeled with 'Some changes are made here.' in the 'BK_another.pl' are also done and no other changes are made.

3. How do I know whether I have successfully started the GPU speedup?

In your README, the following environment variables are added to use the GPU:

# for GPU user
export LD_LIBRARY_PATH=$ABL_HOME/src/logic/lib:/usr/local/cuda:$LD_LIBRARY_PATH

However, I doubt that it should be like this 
	export LD_LIBRARY_PATH=$ABL_HOME/src/logic/lib:/usr/local/cuda/lib64:$LD_LIBRARY_PATH
with the '/lib64' (or your own dir for CUDA lib directory) added.

However, it seems that they both work for the following message appears in both conditions:

2019-08-24 20:14:17.565121: I tensorflow/core/common_runtime/gpu/gpu_device.cc:955] Found device 0 with properties: 
name: GeForce GTX 1080 Ti
major: 6 minor: 1 memoryClockRate (GHz) 1.6575
pciBusID 0000:01:00.0
Total memory: 10.91GiB
Free memory: 10.29GiB
2019-08-24 20:14:17.565133: I tensorflow/core/common_runtime/gpu/gpu_device.cc:976] DMA: 0 
2019-08-24 20:14:17.565136: I tensorflow/core/common_runtime/gpu/gpu_device.cc:986] 0:   Y 
2019-08-24 20:14:17.565141: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0)

4. One more question...

I notice that in the src/main.py you changed the 

	LL.init("-G10g -M6g")
to
	LL.init("--quiet --nosignals --stack_limit=10G")

Would you please explain more about the initial parameters?
 
**_Attachment doesnot support .pl, so I paste them here:

'BK_minus.pl' is:_** 

:- use_module(library(apply)).
:- use_module(library(lists)).
% :- use_module(library(tabling)).
% :- table valid_rules/2, op_rule/2.

%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% DCG (Definite Clause Grammar) parser for equations
%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% symbols to be mapped
digit(1).
digit(0).

% digits
digits([D]) --> [D], { digit(D) }. % empty list [] is not a digit
digits([D | T]) --> [D], !, digits(T), { digit(D) }.
digits(X):-
    phrase(digits(X), X).
% More integrity constraints 1:
% This two clauses forbid the first digit to be 0.
% You may uncomment them to prune the search space
% length(X, L),
% (L > 1 -> X \= [0 | _]; true).

% Equation definition
eq_arg([D]) --> [D], { \+ D == '-', \+ D == '=' }.  % Some changes are made here. We still use + to represent -...   in Coordinate with main.py @Line 298
eq_arg([D | T]) --> [D], !, eq_arg(T), { \+ D == '-', \+ D == '=' }.  % Some changes are made here. We still use + to represent -...  main.py @Line 298
equation(eq(X, Y, Z)) -->
    eq_arg(X), [-], eq_arg(Y), [=], eq_arg(Z).  %  Some changes are made here. We still use + to represent -...   main.py @Line 298
% More integrity constraints 2:
% This clause restricts the length of arguments to be sane,
% You may uncomment them to prune the search space
% { length(X, LX), length(Y, LY), length(Z, LZ),
%   LZ =< max(LX, LY) + 1, LZ >= max(LX, LY) }.
parse_eq(List_of_Terms, Eq) :-
    phrase(equation(Eq), List_of_Terms).

%%%%%%%%%%%%%%%%%%%%%%
%% Bit-wise operation
%%%%%%%%%%%%%%%%%%%%%%
% Abductive calculation with given pseudo-labels, abduces pseudo-labels as well as operation rules
calc(Rules, Pseudo) :-
    calc([], Rules, Pseudo).
calc(Rules0, Rules1, Pseudo) :-
    parse_eq(Pseudo, eq(X,Y,Z)),
    bitwise_calc(Rules0, Rules1, X, Y, Z).

% Bit-wise calculation that handles carrying
bitwise_calc(Rules, Rules1, X, Y, Z) :-
    reverse(X, X1), reverse(Y, Y1), reverse(Z, Z1),
    bitwise_calc_r(Rules, Rules1, X1, Y1, Z1),
    maplist(digits, [X,Y,Z]).
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% MINUS VERSION...
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% 
bitwise_calc_r(Rs, Rs, Y, Y, []).   % bitwise_calc_r(Rs, Rs, [], Y, Y).  addition: [] + Y = Y. Some changes are made here.
bitwise_calc_r(Rs, Rs, X, [], X).   % bitwise_calc_r(Rs, Rs, X, [], X).  addition: X + [] = X. Some changes are made here.
bitwise_calc_r(Rules, Rules1, [D1 | X], [D2 | Y], [D3 | Z]) :-
    abduce_op_rule(my_op([D1],[D2],Sum), Rules, Rules2),
    ((Sum = [D1], Carry = []); (Sum = [C, D1], Carry = [C])),  % Some changes are made here.
    bitwise_calc_r(Rules2, Rules3, X_carried, X, Carry),  % Some changes are made here.
    bitwise_calc_r(Rules3, Rules1, X_carried, Y, Z).  % Some changes are made here.

%%%%%%%%%%%%%%%%%%%%%%%%%
% Abduce operation rules
%%%%%%%%%%%%%%%%%%%%%%%%%
% Get an existed rule
abduce_op_rule(R, Rules, Rules) :-
    member(R, Rules).
% Add a new rule
abduce_op_rule(R, Rules, [R|Rules]) :-
    op_rule(R),
    valid_rules(Rules, R).

% Integrity Constraints
valid_rules([], _).
valid_rules([my_op([X1],[Y1],_)|Rs], my_op([X],[Y],Z)) :-
    op_rule(my_op([X],[Y],Z)),
    [X,Y] \= [X1,Y1],
    [X,Y] \= [Y1,X1],
    valid_rules(Rs, my_op([X],[Y],Z)).
valid_rules([my_op([Y],[X],-Z)|Rs], my_op([X],[Y],Z)) :-  % Some changes are made here.  Z  -->>  -Z
    X \= Y,
    valid_rules(Rs, my_op([X],[Y],Z)).

op_rule(my_op([X],[Y],[Z])) :- digit(X), digit(Y), digit(Z).
% op_rule(my_op([X],[Y],[Z1,Z2])) :- digit(X), digit(Y), digits([Z1,Z2]).
% Some changes are made here.
op_rule(my_op([X1, X2],[Y],Z]) :- digit([X1, X2]), digit(Y), digits(Z).

**_and ‘BK_another’ is:_**

:- use_module(library(apply)).
:- use_module(library(lists)).
% :- use_module(library(tabling)).
% :- table valid_rules/2, op_rule/2.

%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% DCG (Definite Clause Grammar) parser for equations
%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% symbols to be mapped
digit(1).
digit(0).

% digits
digits([D]) --> [D], { digit(D) }. % empty list [] is not a digit
digits([D | T]) --> [D], !, digits(T), { digit(D) }.
digits(X):-
    phrase(digits(X), X).
% More integrity constraints 1:
% This two clauses forbid the first digit to be 0.
% You may uncomment them to prune the search space
% length(X, L),
% (L > 1 -> X \= [0 | _]; true).

% Equation definition
eq_arg([D]) --> [D], { \+ D == '=', \+ D == '+' }.  % + = Some changes are made here. 
eq_arg([D | T]) --> [D], !, eq_arg(T), { \+ D == '=', \+ D == '+' }.  % + = Some changes are made here.
equation(eq(X, Y, Z)) -->
    % eq_arg(X), [+], eq_arg(Y), [=], eq_arg(Z).
    eq_arg(X), [=], eq_arg(Y), [+], eq_arg(Z).  % X=Y+Z. Some changes are made here.
% More integrity constraints 2:
% This clause restricts the length of arguments to be sane,
% You may uncomment them to prune the search space
% { length(X, LX), length(Y, LY), length(Z, LZ),
%   LZ =< max(LX, LY) + 1, LZ >= max(LX, LY) }.
parse_eq(List_of_Terms, Eq) :-
    phrase(equation(Eq), List_of_Terms).

%%%%%%%%%%%%%%%%%%%%%%
%% Bit-wise operation
%%%%%%%%%%%%%%%%%%%%%%
% Abductive calculation with given pseudo-labels, abduces pseudo-labels as well as operation rules
calc(Rules, Pseudo) :-
    calc([], Rules, Pseudo).
calc(Rules0, Rules1, Pseudo) :-
    parse_eq(Pseudo, eq(X,Y,Z)),
    bitwise_calc(Rules0, Rules1, X, Y, Z).

% Bit-wise calculation that handles carrying
bitwise_calc(Rules, Rules1, X, Y, Z) :-
    reverse(X, X1), reverse(Y, Y1), reverse(Z, Z1),
    bitwise_calc_r(Rules, Rules1, X1, Y1, Z1),
    maplist(digits, [X,Y,Z]).
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% ANOTHER VERSION: X = Y + Z (original is X + Y = Z). Actually, you just switch the semantics of '+' and '='.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
bitwise_calc_r(Rs, Rs, Y, Y, []).   % bitwise_calc_r(Rs, Rs, [], Y, Y).  addition: [] + Y = Y.  Some changes are made here.
bitwise_calc_r(Rs, Rs, X, [], X).   % bitwise_calc_r(Rs, Rs, X, [], X).  addition: X + [] = X.  Some changes are made here.
bitwise_calc_r(Rules, Rules1, [D1 | X], [D2 | Y], [D3 | Z]) :-
    abduce_op_rule(my_op([D1],[D2],Sum), Rules, Rules2),
    ((Sum = [D1], Carry = []); (Sum = [C, D1], Carry = [C])),  % D3 -->> D1.  Some changes are made here.
    bitwise_calc_r(Rules2, Rules3, X_carried, X, Carry),  % X, Carry, X_carried  Some changes are made here.
    bitwise_calc_r(Rules3, Rules1, Z, X_carried, Y).  % X_carried, Y, Z  Some changes are made here.

%%%%%%%%%%%%%%%%%%%%%%%%%
% Abduce operation rules
%%%%%%%%%%%%%%%%%%%%%%%%%
% Get an existed rule
abduce_op_rule(R, Rules, Rules) :-
    member(R, Rules).
% Add a new rule
abduce_op_rule(R, Rules, [R|Rules]) :-
    op_rule(R),
    valid_rules(Rules, R).

% Integrity Constraints
valid_rules([], _).

'
valid_rules([my_op([X1],[Y1],_)|Rs], my_op([X],[Y],Z)) :-
    op_rule(my_op([X],[Y],Z)),
    % [X,Y] \= [X1,Y1],
    % [X,Y] \= [Y1,X1],
    [Y,Z] \= [Y1,Z1],
    [Y,Z] \= [Z1,Y1],
    valid_rules(Rs, my_op([X],[Y],Z)).
'
% Some changes are made here.
valid_rules([my_op([Y1],[Z1],_)|Rs], my_op(X,[Y],[Z])) :-
    op_rule(my_op(X,[Y],[Z])),
    % [X,Y] \= [X1,Y1],
    % [X,Y] \= [Y1,X1],
    [Y,Z] \= [Y1,Z1],
    [Y,Z] \= [Z1,Y1],
    valid_rules(Rs, my_op(X,[Y],[Z])).

/*
valid_rules([my_op([Y],[X],Z)|Rs], my_op([X],[Y],Z)) :-
    % X \= Y,
    Y \= Z,
    valid_rules(Rs, my_op([X],[Y],Z)).
*/
% Some changes are made here.
valid_rules([my_op(X,[Z],[Y])|Rs], my_op(X,[Y],[Z])) :-
    % X \= Y,
    Y \= Z,
    valid_rules(Rs, my_op(X,[Y],[Z])).

op_rule(my_op([X],[Y],[Z])) :- digit(X), digit(Y), digit(Z).
% op_rule(my_op([X],[Y],[Z1,Z2])) :- digit(X), digit(Y), digits([Z1,Z2]).
op_rule(my_op([X1, X2],[Y],[Z])) :- digit([X1, X2]), digit(Y), digits([Z]).  % Some changes are made here.

@AbductiveLearning

**Comment by mengshanfeng** [comment]
It seems that my computer tends to crash before the finish of the train process even though I change the max equation length to 6. I notice that the memory of the pc (which is 16G) would be  fully occupied as time passes.

I notice that in the src/main.py you changed the

LL.init("-G10g -M6g")

to

LL.init("--quiet --nosignals --stack_limit=10G")

Would you please explain more about the initial parameters?

**Comment by AbductiveLearning** [comment]
> I just change the folloeing 2 lines:
>
> bitwise_calc_r(Rs, Rs, [], Y, Y).
> bitwise_calc_r(Rs, Rs, X, [], X).
> to
> 
> bitwise_calc_r(Rs, Rs, Y, Y, []).
> bitwise_calc_r(Rs, Rs, X, [], X).
> 
> to make the MINUS version of this equation as well as some other changes labeled with 'Some > changes are made here.' in the 'BK_minus.pl' and no other changes are made.

Hmm, I think only changing the `bigwise_calc_r` here is not enough to capture minus. In order to make minus, you have to enable the background knowledge modelling negative numbers and extend the carry function to allow borrowing.

> export LD_LIBRARY_PATH=$ABL_HOME/src/logic/lib:/usr/local/cuda:$LD_LIBRARY_PATH
> 
> However, I doubt that it should be like this
> export LD_LIBRARY_PATH=$ABL_HOME/src/logic/lib:/usr/local/cuda/lib64:$LD_LIBRARY_PATH
> with the '/lib64' (or your own dir for CUDA lib directory) added.
> 
> However, it seems that they both work for the following message appears in both conditions:

Because if you installed cuda from a package manager, it will create symlink in `/usr/lib`, so it doesn't matter if you export the library path of cuda here.

>  Would you please explain more about the initial parameters?

Please refer to this [link](https://www.swi-prolog.org/pldoc/man?section=cmdline).
