### ISSUE TITLE
Problems setting up and importing LogicLayer module

### ISSUE THREAD

**Issue by hahmed17** [AbductiveLearning/ABL-HED#4]
Hello,

I've been running into issues setting up the LogicLayer module. I set `swipl_include_dir` and `swipl_lib_dir` to my own swi-prolog directories, and when I run setup.py I see this:

```
running install 
running build
running build_ext
running install_lib
running install_egg_info
Removing ../lib/LogicLayer-1.0.egg-info
Writing ../lib/LogicLayer-1.0.egg-info
```

But then when I run main.py, this error comes up:

```
Traceback (most recent call last): 
  File "main.py", line 20, in <module>
    from learn_add import *
  File "./logic/python/learn_add.py", line 9, in <module>
    import LogicLayer as LL
ModuleNotFoundError: No module named 'LogicLayer'
```

I can see the LogicLayer-1.0 egg info file in my directory, and have tried copying the file into other folders, installing packages such as setuptools, and inserting additional paths in learn_add.py, but the module still won't be imported.

**Comment by hahmed17** [comment]
Solved by starting over in a non-Windows server.

**Comment by nophenomena** [comment]
> Solved by starting over in a non-Windows server.

Do you mean that you solved it in a pure non_windows serve like linux instead of wsl?I failed to fix it in wsl2.
