### ISSUE TITLE
swipl-prolog install path seems to have changed

### ISSUE THREAD

**Issue by ZJsheep** [AbductiveLearning/ABL-HED#5]
I used ppa to install swipl on Ubuntu 22.04 today, but there is nothing in `/usr/local/lib/swipl/`. After searching I found it is in `/usr/lib/swi-prolog/` instead. I suppose this is a change in the apt behavior or something?

To adapt to this, two places should be modifed.

1. when setting environment variables, the command `cp /usr/local/lib/swipl/lib/x86_64-linux/libswipl.so $ABL_HOME/src/logic/lib/` should be changed into `cp /usr/lib/swi-prolog/lib/x86_64-linux/libswipl.so $ABL_HOME/src/logic/lib/`
2. in `setup.py`, line 3 - 4 should be changed into
```python
# swipl_include_dir = '/usr/local/lib/swipl/include'
# swipl_lib_dir = '/usr/local/lib/swipl/lib/x86_64-linux'

swipl_include_dir = '/usr/lib/swi-prolog/include'
swipl_lib_dir = '/usr/lib/swi-prolog/lib/x86_64-linux/'
```

After the modification it can now generate equations on ubuntu 22.04.

**Comment by ArghyaPal** [comment]
I think if we install swi-prolog using ``make'', i.e.;
`cd swipl-devel
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr/local ..
make
ctest -j 4
sudo make install` 
then we donot need to change the path.

**Comment by JAYCHOU2020** [comment]
> I think if we install swi-prolog using ``make'', i.e.; `cd swipl-devel mkdir build cd build cmake -DCMAKE_INSTALL_PREFIX=/usr/local .. make ctest -j 4 sudo make install` then we donot need to change the path.

I want to ask that when 5 pictures 1, +, 0, =, 1 are perceived as numbers and symbols 0, +, 1, =, 1, the logic layer gets that this is also an equation, which is still logically true. And then what? How does it optimize to get the pseudo-label back propagated to the perception model and finally get the right perception?

**Comment by JAYCHOU2020** [comment]
> I used ppa to install swipl on Ubuntu 22.04 today, but there is nothing in `/usr/local/lib/swipl/`. After searching I found it is in `/usr/lib/swi-prolog/` instead. I suppose this is a change in the apt behavior or something?
> 
> To adapt to this, two places should be modifed.
> 
> 1. when setting environment variables, the command `cp /usr/local/lib/swipl/lib/x86_64-linux/libswipl.so $ABL_HOME/src/logic/lib/` should be changed into `cp /usr/lib/swi-prolog/lib/x86_64-linux/libswipl.so $ABL_HOME/src/logic/lib/`
> 2. in `setup.py`, line 3 - 4 should be changed into
> 
> ```python
> # swipl_include_dir = '/usr/local/lib/swipl/include'
> # swipl_lib_dir = '/usr/local/lib/swipl/lib/x86_64-linux'
> 
> swipl_include_dir = '/usr/lib/swi-prolog/include'
> swipl_lib_dir = '/usr/lib/swi-prolog/lib/x86_64-linux/'
> ```
> 
> After the modification it can now generate equations on ubuntu 22.04.

I want to ask that when 5 pictures 1, +, 0, =, 1 are perceived as numbers and symbols 0, +, 1, =, 1, the logic layer gets that this is also an equation, which is still logically true. And then what? How does it optimize to get the pseudo-label back propagated to the perception model and finally get the right perception?

**Comment by AbductiveLearning** [comment]
🌟 **New!** [[ABLkit](https://github.com/AbductiveLearning/ABLkit)](https://github.com/AbductiveLearning/ABLkit) released: A toolkit for Abductive Learning with high flexibility, user-friendly interface, and optimized performance. Welcome to try it out!🚀

This repo has been (mostly) superseded by [[ABLkit](https://github.com/AbductiveLearning/ABLkit)](https://github.com/AbductiveLearning/ABLkit). we encourage you to visit the new repository.

**Comment by AbductiveLearning** [comment]
🌟 New! [ABLkit](https://github.com/AbductiveLearning/ABLkit) released: A toolkit for Abductive Learning with high flexibility, user-friendly interface, and optimized performance. Welcome to try it out!🚀

This repo has been (mostly) superseded by [ABLkit](https://github.com/AbductiveLearning/ABLkit). we encourage you to visit the new repository.
