### ISSUE TITLE
是未来解决大模型幻觉的方向之一么，在这方面有什么新成果么

### ISSUE THREAD

**Issue by BEILOP** [AbductiveLearning/ABL-HED#6]

**Comment by JAYCHOU2020** [comment]
> _No description provided._

I want to ask that when 5 pictures 1, +, 0, =, 1 are perceived as numbers and symbols 0, +, 1, =, 1, the logic layer gets that this is also an equation, which is still logically true. And then what? How does it optimize to get the pseudo-label back propagated to the perception model and finally get the right perception?

**Comment by AbductiveLearning** [comment]
We believe ABL has the potential to solve the hallucination problem of large models.

🌟 New! [ABLkit](https://github.com/AbductiveLearning/ABLkit) released: A toolkit for Abductive Learning with high flexibility, user-friendly interface, and optimized performance. Welcome to try it out!🚀
